home/urls.py
from django.urls import path

from . import views

""" To use lettings namespace """
app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
    path("sentry-debug/", views.trigger_error, name="sentrydebug"),
]

lettings/urls.py
from django.urls import path

from . import views

""" To use lettings namespace """
app_name = "lettings"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:letting_id>/", views.letting, name="letting"),
]

oc_lettings_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("home.urls")),
    path("lettings/", include("lettings.urls")),
    path("profiles/", include("profiles.urls")),
    path("admin/", admin.site.urls),
]

profiles/urls.py
from django.urls import path

from . import views

""" To use profiles namespace """
app_name = "profiles"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:username>/", views.profile, name="profile"),
]

lettings/models.py
""" Define lettings models """
from django.db import models
from django.core.validators import MaxValueValidator, MinLengthValidator


class Address(models.Model):
    """Address model.
    Attributes:
    number (int): street number
    street (str): street name
    city (str): city name
    state (str): state abbreviation
    zip_code (int): postal code
    country_iso_code (str): Alpha-3 code as described in the ISO 3166 international standard
    """

    number = models.PositiveIntegerField(validators=[MaxValueValidator(9999)])
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    state = models.CharField(max_length=2, validators=[MinLengthValidator(2)])
    zip_code = models.PositiveIntegerField(validators=[MaxValueValidator(99999)])
    country_iso_code = models.CharField(
        max_length=3, validators=[MinLengthValidator(3)]
    )

    class Meta:
        """db_table (str): the name of the database table to use for the model
        verbose_name_plural (str): plural form of the model"""

        db_table = "oc_lettings_site_address"
        verbose_name_plural = "addresses"

    def __str__(self):
        """Used in print"""
        return f"{self.number} {self.street}"


class Letting(models.Model):
    """Letting model
    attributes:
    title (str): title of the letting
    address (Addres): Address model instance"""

    title = models.CharField(max_length=256)
    address = models.OneToOneField(Address, on_delete=models.CASCADE)

    class Meta:
        """db_table (str): the name of the database table to use for the model"""

        db_table = "oc_lettings_site_letting"

    def __str__(self):
        """Used in print"""
        return self.title

profiles/models.py
""" Define profiles models """
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    """Profile model
    Attributes:
    user (User): User model instance
    favorite_city (string): favorite city of the user"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorite_city = models.CharField(max_length=64, blank=True)

    class Meta:
        """The name of the database table to use for the model"""

        db_table = "oc_lettings_site_profile"

    def __str__(self):
        """Used in print"""
        return self.user.username

home/views.py
import logging
from django.shortcuts import render
from django.views.decorators.http import require_safe


@require_safe
def home(request):
    """Renders home page"""
    return render(request, "home/home.html")


@require_safe
def trigger_error(request):
    try:
        division_by_zero = 1 / 0
        return division_by_zero
    except ZeroDivisionError as e:
        logging.error(str(e))
        return render(request, "error.html", {"message": str(e)}, status=500)

lettings/views.py
import logging
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_safe

from .models import Letting


@require_safe
def index(request):
    """Index of lettings, which lists lettings in the database."""
    lettings_list = Letting.objects.all()
    context = {"lettings_list": lettings_list}
    return render(request, "lettings/index.html", context)


@require_safe
def letting(request, letting_id):
    """Detailed view of a letting.
    Parameters:
    letting_id (int): id of a letting"""
    try:
        letting = get_object_or_404(Letting, id=letting_id)
        context = {
            "title": letting.title,
            "address": letting.address,
        }
        return render(request, "lettings/letting.html", context)
    except Exception as e:
        logging.error(str(e))
        return render(request, "error.html", {"message": str(e)}, status=404)

profiles/views.py
import logging
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_safe


from .models import Profile


@require_safe
def index(request):
    """Index of profiles, which lists the profiles in the database."""
    profiles_list = Profile.objects.all()
    context = {"profiles_list": profiles_list}
    return render(request, "profiles/index.html", context)


@require_safe
def profile(request, username):
    """Detailed view of a profile.
    Parameters:
    username (str): username of a profile"""
    try:
        profile = get_object_or_404(Profile, user__username=username)
        context = {"profile": profile}
        return render(request, "profiles/profile.html", context)
    except Exception as e:
        logging.error(str(e))
        return render(request, "error.html", {"message": str(e)}, status=404)

home/templates/home/home.html
{% extends "base.html" %}
{% block title %}Holiday Homes{% endblock title %}

{% block content %}

	
<div class="container px-5 py-5 text-center">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <h1 class="page-header-ui-title mb-3 display-6">Welcome to Holiday Homes - Soutenance</h1>
        </div>
    </div>
</div>

<div class="container px-5 py-5 text-center">
    <div class="justify-content-center">
        <a class="btn fw-500 ms-lg-4 btn-primary px-10" href="{% url 'profiles:index' %}">
    		Profiles
        </a>
        <a class="btn fw-500 ms-lg-4 btn-primary px-10" href="{% url 'lettings:index' %}">
            Lettings
        </a>
    </div>
</div>

{% endblock %}

lettings/templates/lettings/index.html
{% extends "base.html" %}
{% block title %}
    Lettings
{% endblock title %}
{% block content %}
    <div class="container px-5 py-5 text-center">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h1 class="page-header-ui-title mb-3 display-6">Lettings</h1>
            </div>
        </div>
    </div>
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-10">
                <hr class="mb-0" />
                {% if lettings_list %}
                    <ul class="list-group list-group-flush list-group-careers">
                        {% for letting in lettings_list %}
                            <li class="list-group-item">
                                <a href="{% url 'lettings:letting' letting_id=letting.id %}">{{ letting.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No lettings are available.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container px-5 py-5 text-center">
        <div class="justify-content-center">
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'home:home' %}">Home</a>
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'profiles:index' %}">Profiles</a>
        </div>
    </div>
{% endblock %}

lettings/templates/lettings/letting.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block content %}
    <div class="container px-5 py-5 text-center">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h1 class="page-header-ui-title mb-3 display-6">{{ title }}</h1>
            </div>
        </div>
    </div>
    <div class="container px-5 py-5 text-center">
        <div class="card">
            <div class="card-body">
                <div class="icon-stack icon-stack-lg bg-primary text-white mb-3">
                    <i data-feather="home"></i>
                </div>
                <p>{{ address.number }} {{ address.street }}</p>
                <p>{{ address.city }}, {{ address.state }} {{ address.zip_code }}</p>
                <p>{{ address.country_iso_code }}</p>
            </div>
        </div>
    </div>
    <div class="container px-5 py-5 text-center">
        <div class="justify-content-center">
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'lettings:index' %}">
                <i class="ms-2" data-feather="arrow-right"></i>
                Back
            </a>
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'home:home' %}">Home</a>
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'profiles:index' %}">Profiles</a>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/index.html
{% extends "base.html" %}
{% block title %}
    Profiles
{% endblock title %}
{% block content %}
    <div class="container px-5 py-5 text-center">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h1 class="page-header-ui-title mb-3 display-6">Profiles</h1>
            </div>
        </div>
    </div>
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-10">
                <hr class="mb-0" />
                {% if profiles_list %}
                    <ul class="list-group list-group-flush list-group-careers">
                        {% for profile in profiles_list %}
                            <li class="list-group-item">
                                <a href="{% url 'profiles:profile' username=profile.user.username %}">{{ profile.user.username }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No profiles are available.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container px-5 py-5 text-center">
        <div class="justify-content-center">
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'home:home' %}">Home</a>
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'lettings:index' %}">Lettings</a>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% block title %}
    {{ profile.user.username }}
{% endblock title %}
{% block content %}
    <div class="container px-5 py-5 text-center">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h1 class="page-header-ui-title mb-3 display-6">{{ profile.user.username }}</h1>
            </div>
        </div>
    </div>
    <div class="container px-5 py-5 text-center">
        <div class="card">
            <div class="card-body">
                <div class="icon-stack icon-stack-lg bg-primary text-white mb-3">
                    <i data-feather="user"></i>
                </div>
                <p>
                    <strong>First name :</strong> {{ profile.user.first_name }}
                </p>
                <p>
                    <strong>Last name :</strong> {{ profile.user.last_name }}
                </p>
                <p>
                    <strong>Email :</strong> {{ profile.user.email }}
                </p>
                <p>
                    <strong>Favorite city :</strong> {{ profile.favorite_city }}
                </p>
            </div>
        </div>
    </div>
    <div class="container px-5 py-5 text-center">
        <div class="justify-content-center">
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'profiles:index' %}">
                <i class="ms-2" data-feather="arrow-left"></i>
                Back
            </a>
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'home:home' %}">Home</a>
            <a class="btn fw-500 ms-lg-4 btn-primary px-10"
               href="{% url 'lettings:index' %}">Lettings</a>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link rel="icon"
              type="image/x-icon"
              href="{% static 'assets/img/logo.png' %}" />
        <script data-search-pseudo-elements
                defer
                src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.24.1/feather.min.js"
                crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="layoutDefault">
            <div id="layoutDefault_content">
                <main>
                    <!-- Navbar-->
                    <nav class="navbar  navbar-expand-lg bg-white navbar-light">
                        <div class="container">
                            <a class="navbar-brand" href="{% url 'home:home' %}">
                                <img class="img-responsive"
                                     src="{% static 'assets/img/logo.png' %}"
                                     width="70px"
                                     height="70px"
                                     alt="Logo Orange County Lettings" />
                            </a>
                            <div>
                                <a class="btn fw-500 ms-lg-4 btn-primary"
                                   href="{% url 'profiles:index' %}">Profiles</a>
                                <a class="btn fw-500 ms-lg-4 btn-primary"
                                   href="{% url 'lettings:index' %}">Lettings</a>
                            </div>
                        </div>
                    </nav>
                    <hr class="m-0" />
                    {% block content %}{% endblock %}
                </main>
            </div>
            <div id="layoutDefault_footer">
                <footer class="footer pb-5 mt-auto bg-dark footer-dark">
                    <div class="container px-5">
                        <hr class="my-5" />
                        <div class="row gx-5 align-items-center">
                            <div class="col-md-6 small">Copyright &copy; Orange County Lettings 2023</div>
                            <div class="col-md-6 text-md-end small">
                                <a href="#!">Privacy Policy</a>
                                &middot;
                                <a href="#!">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
            AOS.init({
                disable: 'mobile',
                duration: 600,
                once: true,
            });
        </script>
    </body>
</html>

templates/error.html
{% extends "base.html" %}
{% block title %}
    Error message
{% endblock title %}
{% block content %}
    <main class="container">
        <div class="container px-5 py-5 text-center">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <h1 class="page-header-ui-title mb-3 display-6">Houston, we have a problem!</h1>
                </div>
            </div>
        </div>
        <div class="container px-5">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-10">
                    <p class="justify-content-center">
                        Problem detail : <b>{{ message }}</b>
                    </p>
                    <p>Here is a list of useful links to go out:</p>
                    <ul class="justify-content-center">
                        <li>
                            <a href="{% url 'home:home' %}" alt="Home">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'profiles:index' %}" alt="Profiles">Profiles</a>
                        </li>
                        <li>
                            <a href="{% url 'lettings:index' %}" alt="Lettings">Lettings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </main>
{% endblock %}